<?php

return [
    // The Telegram BOT api token
    'token' => env('TELEGRAM_TOKEN'),

    // if the webhook mode must validate the incoming IP range is from a telegram server
    'safe_mode' => env('APP_ENV', 'local') === 'production',

    // Extra or specific configurations
    'config' => [
        'timeout' => 60,               // HTTP-клиент
        'enable_http2' => false,       // HTTP/1.1 — стабильнее за прокси/в нестабильной сети
        'client' => [
            'expect' => false,         // без Expect: 100-continue
        ],
        'polling' => [
            // long-poll; в ограниченных окружениях можно снизить через TELEGRAM_POLL_TIMEOUT=1
            'timeout' => (int) env('TELEGRAM_POLL_TIMEOUT', 20),
        ],
    ],

    // Set if the service provider should automatically load
    // handlers from /routes/telegram.php
    'routes' => true,

    // Enable or disable Nutgram mixins
    'mixins' => false,

    // Path to save files generated by nutgram:make command
    'namespace' => app_path('Telegram'),

    // Set log channel
    'log_channel' => env('TELEGRAM_LOG_CHANNEL', 'null'),
];
